In [2]:
import numpy as np

num_patients = 5
visits = 10
num_features = 25

# generating random EHR data
ehr_data = np.random.rand(num_patients, visits, num_features)

# sample sequence lengths for each patient
seq_lengths = np.random.randint(1, visits + 1, size=num_patients)
print(ehr_data)
# display generated data
# for i in range(num_patients):
#     print(f"Patient {i + 1} - Sequence Length: {seq_lengths[i]}")
#     print(ehr_data[i, :seq_lengths[i], :])
#     print("-" * 40)

#[[  1.           0.          82.           0.21         0.
#     0.           0.           0.           0.           0.
#     1.           0.           0.           0.           0.
#     0.           0.           0.           0.           1.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           1.           0.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           0.           0.
#     0.           1.           0.           0.           0.
#     0.           0.           0.           0.         128.
#    57.         170.          87.         100.          19.
#   104.          36.5         69.5356536    7.4          0.
#     1.           0.           1.           1.           0.
#     1.           0.           1.           0.           1.
#     1.           1.           1.           1.           1.
#     0.        ]
#  [  1.           0.          51.           0.21         0.
#     0.           0.           0.           0.           0.
#     1.           0.           0.           0.           0.
#     0.           0.           0.           0.           1.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           1.           0.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           0.           0.
#     0.           1.           0.           0.           0.
#     0.           0.           0.           0.         128.
#    63.         170.          75.         100.          17.
#   144.          36.5         69.5356536    7.4          0.
#     1.           0.           0.           0.           0.
#     0.           0.           1.           0.           1.
#     1.           1.           1.           0.           0.
#     0.        ]
#  [  1.           0.          52.           0.21         0.
#     0.           0.           0.           0.           0.
#     1.           0.           0.           0.           0.
#     0.           0.           0.           0.           1.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           1.           0.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           0.           0.
#     0.           1.           0.           0.           0.
#     0.           0.           0.           0.         128.
#    63.         170.          80.         100.          18.
#   161.          36.5         69.5356536    7.4          0.
#     1.           0.           0.           0.           0.
#     0.           0.           1.           0.           1.
#     1.           1.           1.           0.           0.
#     0.        ]
#  [  1.           0.          58.           0.21         0.
#     0.           0.           0.           0.           0.
#     1.           0.           0.           0.           0.
#     0.           0.           0.           0.           1.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           1.           0.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           0.           0.
#     0.           1.           0.           0.           0.
#     0.           0.           0.           0.         128.
#    57.         170.          78.          96.          22.
#   139.          36.5         69.5356536    7.4          0.
#     1.           0.           0.           0.           0.
#     0.           0.           1.           0.           1.
#     1.           1.           1.           0.           0.
#     0.        ]
#  [  1.           0.          57.           0.21         0.
#     0.           0.           0.           0.           0.
#     1.           0.           0.           0.           0.
#     0.           0.           0.           0.           1.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           1.           0.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           0.           0.
#     0.           1.           0.           0.           0.
#     0.           0.           0.           0.         128.
#    59.         170.          88.         100.          21.
#   174.          36.77777778  69.5356536    7.4          0.
#     1.           0.           0.           0.           0.
#     0.           0.           1.           0.           1.
#     1.           1.           1.           1.           0.
#     0.        ]
#  [  1.           0.          56.           0.21         0.
#     0.           0.           0.           0.           0.
#     1.           0.           0.           0.           0.
#     0.           0.           0.           0.           1.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           1.           0.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           0.           0.
#     0.           1.           0.           0.           0.
#     0.           0.           0.           0.         168.
#    60.         170.          86.          99.          17.
#   166.          36.77777778  69.5356536    7.4          0.
#     1.           0.           0.           0.           0.
#     0.           1.           1.           0.           1.
#     1.           1.           1.           0.           0.
#     0.        ]
#  [  1.           0.          75.           0.21         0.
#     0.           0.           0.           0.           0.
#     1.           0.           0.           0.           0.
#     0.           0.           0.           0.           1.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           1.           0.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           0.           0.
#     0.           1.           0.           0.           0.
#     0.           0.           0.           0.         168.
#    59.         170.         100.         100.          20.
#   174.          36.77777778  69.5356536    7.4          0.
#     1.           0.           0.           0.           0.
#     0.           0.           1.           0.           1.
#     1.           1.           1.           0.           0.
#     0.        ]
#  [  1.           0.          65.           0.21         0.
#     0.           0.           0.           0.           0.
#     1.           0.           0.           0.           0.
#     0.           0.           0.           0.           1.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           1.           0.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           0.           0.
#     0.           1.           0.           0.           0.
#     0.           0.           0.           0.         168.
#    58.         170.          87.         100.          20.
#   165.          36.77777778  69.5356536    7.4          0.
#     1.           0.           0.           0.           0.
#     0.           0.           1.           0.           1.
#     1.           1.           1.           0.           0.
#     0.        ]
#  [  1.           0.          65.           0.21         0.
#     0.           0.           0.           0.           0.
#     1.           0.           0.           0.           0.
#     0.           0.           0.           0.           1.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           1.           0.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           0.           0.
#     0.           1.           0.           0.           0.
#     0.           0.           0.           0.         168.
#    58.         170.          92.          99.          23.
#   183.          36.38888889  69.5356536    7.4          0.
#     1.           0.           1.           1.           0.
#     1.           0.           1.           0.           1.
#     1.           1.           1.           1.           0.
#     0.        ]
#  [  1.           0.          80.           0.21         0.
#     0.           0.           0.           0.           0.
#     1.           0.           0.           0.           0.
#     0.           0.           0.           0.           1.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           1.           0.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           0.           0.
#     0.           1.           0.           0.           0.
#     0.           0.           0.           0.         168.
#    57.         170.          91.          99.          25.
#   139.          36.38888889  69.5356536    7.4          0.
#     1.           0.           0.           0.           0.
#     0.           0.           1.           0.           1.
#     1.           1.           1.           0.           0.
#     0.        ]
#  [  1.           0.          80.           0.21         0.
#     0.           0.           0.           0.           0.
#     1.           0.           0.           0.           0.
#     0.           0.           0.           0.           1.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           1.           0.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           0.           0.
#     0.           1.           0.           0.           0.
#     0.           0.           0.           0.         168.
#    57.         170.          91.          99.          25.
#   139.          36.38888889  69.5356536    7.4          0.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           0.           0.
#     0.           0.           0.           0.           0.
#     0.        ]])

[[[0.98373511 0.31514595 0.13016714 ... 0.10752305 0.54219303 0.57591221]
  [0.52117864 0.0361533  0.49902663 ... 0.53273913 0.35918354 0.2535231 ]
  [0.72055459 0.62445621 0.15731397 ... 0.20032697 0.88436469 0.75762683]
  ...
  [0.97987371 0.41895427 0.28907045 ... 0.48231164 0.61012879 0.53321011]
  [0.36448691 0.34937776 0.23026127 ... 0.74002013 0.64681448 0.58663534]
  [0.84478555 0.0079708  0.15277623 ... 0.60701803 0.74931947 0.72910822]]

 [[0.65590634 0.38712771 0.84674326 ... 0.93136666 0.98796896 0.08858608]
  [0.9161026  0.01879259 0.88627579 ... 0.21315664 0.4869541  0.34398769]
  [0.4469226  0.95749072 0.87398558 ... 0.43176709 0.70712627 0.97435327]
  ...
  [0.16787567 0.36548324 0.06444975 ... 0.02233911 0.49225134 0.30334089]
  [0.22549435 0.80218775 0.77640984 ... 0.05289779 0.03155595 0.83327268]
  [0.62589609 0.70761597 0.80243703 ... 0.63072483 0.22393001 0.35493249]]

 [[0.39199594 0.94519004 0.40528876 ... 0.51594962 0.3226206  0.60497774]
  [0.69029764 0.653607

In [3]:
import numpy as np
ehr_datas = np.array([
    [0.0, 81.0, 0.21, 2 , 5, 13, 3, 128.0, 150.0, 170.0, 85.0, 100.0, 24.0, 99.0, 36.6, 81.0, 7.4],
    [0.0, 51.0, 0.21, 3 , 6, 14, 3, 128.0, 63.0, 170.0, 75.0, 100.0, 17.0, 144.0, 36.5, 69.5356536, 7.4],
    [0.0, 52.0, 0.21, 4 , 2, 15, 3, 128.0, 63.0, 170.0, 80.0, 100.0, 18.0, 161.0, 36.5, 69.5356536, 7.4]
])

print(ehr_datas.shape)
print(ehr_datas)



(3, 17)
[[  0.         81.          0.21        2.          5.         13.
    3.        128.        150.        170.         85.        100.
   24.         99.         36.6        81.          7.4      ]
 [  0.         51.          0.21        3.          6.         14.
    3.        128.         63.        170.         75.        100.
   17.        144.         36.5        69.5356536   7.4      ]
 [  0.         52.          0.21        4.          2.         15.
    3.        128.         63.        170.         80.        100.
   18.        161.         36.5        69.5356536   7.4      ]]


In [4]:
normal_values= {'Capillary refill rate': '0.0', 'Diastolic blood pressure': '59.0', 'Fraction inspired oxygen': '0.21',
                'Glascow coma scale eye opening': '4 Spontaneously', 'Glascow coma scale motor response': '6 Obeys Commands', 
                'Glascow coma scale total': '15', 'Glascow coma scale verbal response': '5 Oriented', 'Glucose': '128.0', 
                'Heart Rate': '86', 'Height': '170.0', 'Mean blood pressure': '77.0', 'Oxygen saturation': '98.0', 
                'Respiratory rate': '19', 'Systolic blood pressure': '118.0', 'Temperature': '36.6', 'Weight': '81.0', 'pH': '7.4'}

print(len(normal_values))

17


In [7]:
def vertical_mask(data, max_percent=0.4):
    # mask over each timestep (t, features)
    length = data.shape[0]
    size = int(np.random.randint(low=0, high=max(int(max_percent*length),1), size=1))
    a = np.zeros(length , dtype=int)
    a[:size] = 1
    np.random.shuffle(a)
    a = a.astype(bool)
    data[2,:] = np.array([value for value in normal_values.values()])
    return data
vertical_mask(ehr_datas)

ValueError: could not convert string to float: '4 Spontaneously'

In [9]:
def horizontal_mask(data, max_percent=0.4):
    # mask over each feature (t, features)
    length = data.shape[1] - 1
    size = int(np.random.randint(low=0, high=max(int(max_percent*length),1), size=1))
    features = np.unique(np.random.randint(low=1, high=length, size=size))
    for i in features:
        print(data[:, i+1])
        print(list(normal_values.values())[i])
        data[:,i] = list(normal_values.values())[i]
    return data
horizontal_mask(ehr_datas)

array([[200, 200,   3,   4,   5],
       [  6,   7,   8,   9,  10]])

In [8]:
def drop_start(data, max_percent=0.4):
    length = data.shape[0]
    start = int(np.random.randint(low=0, high=max(int(max_percent*length),1), size=1))
    return data[start:,:]
drop_start(ehr_datas)

array([[0.00000000e+000, 8.10000000e+001, 2.10000000e-001,
        2.00000000e+000, 5.00000000e+000, 1.30000000e+001,
        3.00000000e+000, 1.28000000e+002, 1.50000000e+002,
        1.70000000e+002, 8.50000000e+001, 1.00000000e+002,
        2.40000000e+001, 9.90000000e+001, 3.66000000e+001,
        8.10000000e+001, 7.40000000e+000],
       [0.00000000e+000, 5.10000000e+001, 2.10000000e-001,
        3.00000000e+000, 6.00000000e+000, 1.40000000e+001,
        3.00000000e+000, 1.28000000e+002, 6.30000000e+001,
        1.70000000e+002, 7.50000000e+001, 1.00000000e+002,
        1.70000000e+001, 1.44000000e+002, 3.65000000e+001,
        6.95356536e+001, 7.40000000e+000],
       [0.00000000e+000, 5.90000000e+001, 2.10000000e-001,
        6.01347002e-154, 6.01355004e-154, 6.01347002e-154,
        6.01347002e-154, 1.12590726e-153, 6.01347002e-154,
        6.01771527e-154, 6.01355004e-154, 6.01347002e-154,
        6.01347002e-154, 1.12576158e-153, 6.01347002e-154,
        6.01347033e-154, 6.96

In [9]:
begin_pos = [0, 4]  
test_arr = np.array ([[200, 200, 3 , 4 , 5] , [ 6, 7 ,8, 9, 10]])
def gaussian_blur(data, begin_pos):
    mean, std = 0 , 2
    print( np.random.normal(mean, std, (data.shape[0], len(begin_pos))))
    print(data.shape[0], len(begin_pos))
    data[:, begin_pos] = data[:, begin_pos]  + np.random.normal(mean, std, (data.shape[0], len(begin_pos)))
    return data
gaussian_blur(test_arr, begin_pos)


[[-0.01515564  0.22723883]
 [-0.08224597 -1.28357808]]
2 2


array([[202, 200,   3,   4,   6],
       [  4,   7,   8,   9,   9]])

In [10]:
import random
def rotation(data):
    choice = random.randint(0,1)
    if choice:
        return np.flip(data, axis=0)
    return data
rotation(test_arr)

array([[  6,   7,   8,   9,  10],
       [200, 200,   3,   4,   5]])

In [13]:
def downsample(data):
    if data.shape[0] < 20:
        return data
    step = choice([1, 2, 3])
    return data[::step]
downsample(ehr_datas)

NameError: name 'choice' is not defined

In [12]:
arr = np.random.randint(0,6,[5,5])
print(arr)
arr.mean(axis=0)
arr.std(axis=0)
arr = (arr - arr.mean(axis=0)) / arr.std(axis=0)
arr
arr.std(axis=0)

[[1 3 4 0 1]
 [0 1 2 1 1]
 [1 1 5 0 2]
 [1 5 1 5 0]
 [5 0 2 1 3]]


array([1., 1., 1., 1., 1.])

In [ ]:
def augment(serial, stepped, aug_count):
    
    # randomly creates 10*aug_count augmentated versions of the input trajectory
    # by truncating / masking / shuffling combinations of events within the list
    try:
        z = [shuffle_stepped(stepped, len(serial)) for _ in range(aug_count)]
        augmentation_selector = np.random.choice([0, 1], 10*aug_count, p=[0.7, 0.3], replace=True)
        first_data = min(np.nonzero(serial)[0])
        data_elems = len(serial[first_data:])
        x = [mask_serial(z[i//10], first_data, data_elems) for i, x in enumerate(augmentation_selector) if x == 0]
        y = [truncate_serial(z[i//10], first_data, data_elems) for i, x in enumerate(augmentation_selector) if x == 1] 
        return x + y
    except:
        return [serial.astype(int) for _ in range(aug_count*20)]
    
def mask_serial(serial, first_data, data_elems):
    # removes somewhere between 1 and half the number of elements in the list - random mask
    mask_num = np.random.randint(1, max(2, data_elems//2))
    mask = np.random.choice(list(range(first_data, len(serial))), data_elems - mask_num, replace=False)
    return np.hstack([[0]*(mask_num+first_data), serial[sorted(mask)]]).astype(np.int64)   

def shuffle_stepped(stepped, n):
    # shuffles events that occur within the same 1hr period and reassembles into a serial trajectory
    try:
        for i in range(stepped.shape[0]):
            nz = np.nonzero(stepped[i])[0]
            if len(nz) > 0:
                first_data = min(nz)
                np.random.shuffle(stepped[i][first_data:])
        s = stepped[np.nonzero(stepped)].flatten()
        return np.hstack([[0]*(max(0, n-len(s))), s[-n:]]).astype(np.int64)
    except:
        return np.array(stepped)

def truncate_serial(serial, first_data, data_elems):
    # removes somewhere between 1 and a third of the number of elements in the list - drops oldest events
    truncate_num = np.random.randint(1, max(2, data_elems//3))
    return np.hstack([[0]*(first_data+truncate_num), serial[first_data + truncate_num:]]).astype(np.int64)